package net.cellingo.sequence_tools.annotation;

import net.cellingo.sequence_tools.alignment.HairpinAlignment;

public class SequenceHairpinElement extends SequenceElement {
    private static final long serialVersionUID = 1L;
    private HairpinAlignment hairpin;

    public SequenceHairpinElement(HairpinAlignment hairpin) {
        super(SequenceElement.getNextAutogeneratedId());
        this.setHairpin(hairpin);
    }

    /**
     * @param hairpin the hairpin to set
     */
    public void setHairpin(HairpinAlignment hairpin) {
        this.hairpin = hairpin;
    }

    /**
     * @return the hairpin
     */
    public HairpinAlignment getHairpin() {
        return hairpin;
    }

    public int getForwardStart() {
        return hairpin.getTopParent().getSequenceCoordinates().getStart();
    }

    public int getForwardStop() {
        return hairpin.getTopParent().getSequenceCoordinates().getStop();
    }

    public int getReverseStart() {
        return hairpin.getBottomParent().getSequenceCoordinates().getStop();
    }

    public int getReverseStop() {
        return hairpin.getBottomParent().getSequenceCoordinates().getStart();
    }

}
